on:
  workflow_call:
    inputs:
      target_name:
        required: true
        type: string
      opensbi_repo:
        required: true
        type: string
      opensbi_ref:
        required: true
        type: string

jobs:
  build-opensbi:
    name: Build OpenSBI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: ctx
      - name: Cache OpenSBI Build
        id: cache-opensbi-build
        uses: actions/cache@v5
        with:
          path: dist
          key: cache-opensbi-build-${{ inputs.target_name }}-ref=${{ inputs.opensbi_ref }}-wf=${{ hashFiles('ctx/.github/workflows/.sophgo-sg204x.opensbi-build.yml') }}
      - name: Setup Toolchains
        if: ${{ steps.cache-opensbi-build.outputs.cache-hit != 'true' }}
        id: setup-gcc-toolchain
        uses: ./ctx/.github/actions/riscv64-gcc-toolchain
      - name: Checkout OpenSBI
        if: ${{ steps.cache-opensbi-build.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.opensbi_repo }}
          path: opensbi
          ref: ${{ inputs.opensbi_ref }}
          fetch-depth: 1
      - name: Build OpenSBI
        if: ${{ steps.cache-opensbi-build.outputs.cache-hit != 'true' }}
        run: |
          make -j"$(nproc)" -C opensbi O=$(pwd)/build CROSS_COMPILE=${{ steps.setup-gcc-toolchain.outputs.full-prefix }} PLATFORM=generic FW_PIC=y BUILD_INFO=y
      - name: Collect OpenSBI Binary
        if: ${{ steps.cache-opensbi-build.outputs.cache-hit != 'true' }}
        run: |
          mkdir dist
          cp build/platform/generic/firmware/fw_dynamic.bin dist/fw_dynamic.bin
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "opensbi-${{ inputs.target_name }}"
          path: dist
