name: SOPHGO SG2042

on:
  push:
    paths:
      - '.github/workflows/sophgo-sg2042.yml'
      - '.github/workflows/.sophgo-sg204x.*'
      - 'sophgo/sg2042/**'

jobs:

  build-zsbl-sg2042:
    name: Build ZSBL for SG2042
    uses: ./.github/workflows/.sophgo-sg204x.zsbl-build.yml
    with:
      target_name: sophgo-sg2042
      zsbl_repo: revyos/zsbl
      # Branch sg204x as of 20260227
      zsbl_ref: 45054e711d81fbfa1c2167829402d26795199ae7
      zsbl_defconfig: sg2042_defconfig

  build-opensbi-sg2042:
    name: Build OpenSBI for SG2042
    uses: ./.github/workflows/.sophgo-sg204x.opensbi-build.yml
    with:
      target_name: sophgo-sg2042
      opensbi_repo: sophgo/opensbi
      # Branch sg2042-dev as of 20260225
      opensbi_ref: adc7ba17f3726aee599bc6fc879fbc569fbbba71

  build-u-root:
    name: Build u-root
    uses: ./.github/workflows/.sophgo-sg204x.u-root-build.yml
    with:
      target_name: sophgo-sg204x
      u_root_repo: openeuler-riscv/u-root
      # Branch sg204x-v0.15 as of 20260225
      u_root_ref: 69595b5c67cb59b0afb9744d13625b9df6869a64

  build-kernel-sg2042:
    name: Build Kernel for SG2042
    uses: ./.github/workflows/.sophgo-sg204x.kernel-build.yml
    with:
      target_name: sophgo-sg2042
      kernel_repo: sophgo/linux-riscv
      # Branch sg2042-dev-6.6 as of 20260226
      kernel_ref: 15143c39ba8d2ebd6c47e7eabcbf2a3b19960532
      kernel_defconfig: sophgo_mango_normal_defconfig

  prepare-firmware-content-sg2042:
    name: Prepare Firmware Contents for SG2042
    needs:
      - build-zsbl-sg2042
      - build-opensbi-sg2042
      - build-u-root
      - build-kernel-sg2042
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - firmware_target_name: linuxboot-sophgo-sg2042
            zsbl_target_name: sophgo-sg2042
            opensbi_target_name: sophgo-sg2042
            u_root_target_name: sophgo-sg204x
            kernel_target_name: sophgo-sg2042
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          path: u-boot-build
      - name: Setup Work Dirs
        run: |
          mkdir -p dist/riscv64
      - name: Fetch Pre-built ZSBL
        uses: actions/download-artifact@v5
        with:
          name: "zsbl-${{ matrix.zsbl_target_name }}"
          path: dist
          merge-multiple: true
      - name: Copy fip.bin
        run: |
          cp u-boot-build/sophgo/sg2042/blobs/fip.bin dist
      - name: Fetch Pre-built OpenSBI
        uses: actions/download-artifact@v5
        with:
          name: "opensbi-${{ matrix.opensbi_target_name }}"
          path: dist/riscv64
          merge-multiple: true
      - name: Fetch Pre-built u-root
        uses: actions/download-artifact@v5
        with:
          name: "u-root-${{ matrix.u_root_target_name }}"
          path: dist/riscv64
          merge-multiple: true
      - name: Fetch Pre-built Kernel
        uses: actions/download-artifact@v5
        with:
          name: "kernel-${{ matrix.kernel_target_name }}"
          path: dist/riscv64
          merge-multiple: true
      - name: Install dtc
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler
      - name: Fixup dtb name
        run: |
          dtc dist/riscv64/mango-milkv-pioneer.dtb | sed 's/console=tty1 //' | dtc > dist/riscv64/sg2042-milkv-pioneer.dtb
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "collected-${{ matrix.firmware_target_name }}"
          path: dist

  pack-sd-boot-firmware-sg2042:
    name: Pack SD Card Boot Image for SG2042
    needs: prepare-firmware-content-sg2042
    uses: ./.github/workflows/.sophgo-sg204x.pack-sdimg.yml
    with:
      firmware_target_name: linuxboot-sophgo-sg2042

  pack-nor-boot-firmware-sg2042:
    name: Pack NOR Flash Boot Image for SG2042
    needs: prepare-firmware-content-sg2042
    runs-on: ubuntu-latest
    env:
      PACKTOOL_PATH: /opt/sophgo-packtool/pack
    strategy:
      matrix:
        include:
          - firmware_target_name: linuxboot-sophgo-sg2042
    steps:
      - name: Setup Work Dirs
        run: |
          mkdir -p staging
          mkdir -p dist
      - name: Cache Pack-Tool Build
        id: cache-pack-tool-build
        uses: actions/cache@v5
        with:
          path: ${{ env.PACKTOOL_PATH }}
          key: cache-pack-tool-build-${{ runner.os }}-ref=${{ github.sha }}
      - uses: actions/checkout@v6
        if: ${{ steps.cache-pack-tool-build.outputs.cache-hit != 'true' }}
        with:
          fetch-depth: 1
          path: bootloader-build
      - name: Install Dependencies
        if: ${{ steps.cache-pack-tool-build.outputs.cache-hit != 'true' }}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc make
      - name: Build Pack-Tool
        if: ${{ steps.cache-pack-tool-build.outputs.cache-hit != 'true' }}
        run: |
          make -C bootloader-build/sophgo/sg204x-pack-tool/
          mkdir -p "$(dirname "${PACKTOOL_PATH}")"
          cp bootloader-build/sophgo/sg204x-pack-tool/pack ${PACKTOOL_PATH}
      - name: Fetch Collected Files
        uses: actions/download-artifact@v5
        with:
          name: "collected-${{ matrix.firmware_target_name }}"
          path: staging
          merge-multiple: true
      - name: Pack Firmware
        run: |
          BINARY_FILE="dist/firmware-${{ matrix.firmware_target_name }}-nor-boot.bin"
          "${PACKTOOL_PATH}" -a -p fip.bin -t 0x600000 -f "staging/fip.bin" -o 0x30000 "${BINARY_FILE}"
          "${PACKTOOL_PATH}" -a -p zsbl.bin -t 0x600000 -f "staging/zsbl.bin" -l 0x40000000 "${BINARY_FILE}"
          "${PACKTOOL_PATH}" -a -p fw_dynamic.bin -t 0x600000 -f "staging/riscv64/fw_dynamic.bin" -l 0x0 "${BINARY_FILE}"
          "${PACKTOOL_PATH}" -a -p riscv64_Image -t 0x600000 -f "staging/riscv64/riscv64_Image" -l 0x2000000 "${BINARY_FILE}"
          "${PACKTOOL_PATH}" -a -p initrd.img -t 0x600000 -f "staging/riscv64/initrd.img" -l 0x30000000 "${BINARY_FILE}"
          for dtbfile in staging/riscv64/*.dtb; do
            if [ -e "${dtbfile}" ]; then
              "${PACKTOOL_PATH}" -a -p "$(basename "${dtbfile}")" -t 0x600000 -f "${dtbfile}" -l 0x20000000 "${BINARY_FILE}"
            fi
          done
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "firmware-${{ matrix.firmware_target_name }}-nor-boot"
          path: dist
  release:
    name: Release Firmware for SOPHGO SG2042
    needs:
      - pack-sd-boot-firmware-sg2042
      - pack-nor-boot-firmware-sg2042
    uses: ./.github/workflows/artifact-release.yml
    permissions:
      contents: write
    secrets: inherit
    with:
      tag_name: release-sophgo-sg2042
      release_name: Boot Firmware for SOPHGO SG2042
      run_id: ${{github.run_id}}
      artifact_pattern: "firmware-*"
